sonar.projectKey=Develophys_aonde-tem
sonar.organization=develophys

sonar.sources=apps/api/src,apps/web/src,packages/contracts/src,packages/domain/src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.turbo/**,**/*.d.ts

sonar.sourceEncoding=UTF-8
